version: '3.8'

services:
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: odla-payment-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CONCORDIUM_NODE_HOST=grpc.testnet.concordium.com
      - CONCORDIUM_NODE_PORT=20000
      - NETWORK_ID=100
    networks:
      - odla-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: odla-server
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
    volumes:
      - ./data:/app/data
      - ./config.docker.json:/app/config.json:ro
    networks:
      - odla-network
    depends_on:
      payment-service:
        condition: service_healthy
    restart: unless-stopped

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: odla-node
    ports:
      - "8001:8001"
    environment:
      - NODE_PORT=8001
      - OLLAMA_HOST=http://host.docker.internal:11434
      - SERVER_URL=http://server:8000
      - CONCORDIUM_ADDRESS=4nB44APqJ6YFv52DueVEYgVw3x57zaEew3nu3uy2YqNiHcELM3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
      - ./config.docker.json:/app/config.json:ro
    networks:
      - odla-network
    depends_on:
      - server
      - payment-service
    restart: unless-stopped

networks:
  odla-network:
    driver: bridge

volumes:
  data:
